#!/bin/sh
# vnext-ai-toolkit SessionStart hook.
# Warns (via additionalContext) when
#   (1) the workspace's toolkit-owned files were generated by an older plugin version than the one
#       currently installed, and
#   (2) the workspace's vnext.config.json runtimeVersion differs from the runtime version the
#       toolkit's knowledge describes (plugin.json .vnext.knownRuntimeVersion).
# Never blocks: always exits 0. No jq dependency — plain sed scraping of flat string fields.

# Not a vNext workspace → silent no-op (this hook fires in every project; plugins are global).
[ -f "vnext.config.json" ] || exit 0

plugin_manifest="${CLAUDE_PLUGIN_ROOT}/.claude-plugin/plugin.json"
[ -f "$plugin_manifest" ] || exit 0

# scrape "<key>": "<value>" (first occurrence) from a file
scrape() { sed -n "s/.*\"$1\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*/\1/p" "$2" | head -1; }

plugin_version=$(scrape version "$plugin_manifest")
[ -n "$plugin_version" ] || exit 0
known_runtime=$(scrape knownRuntimeVersion "$plugin_manifest")

workspace_version=""
if [ -f ".claude/vnext-toolkit.json" ]; then
    workspace_version=$(scrape toolkitVersion ".claude/vnext-toolkit.json")
fi
if [ -z "$workspace_version" ] && [ -f "CLAUDE.md" ]; then
    # <!-- vnext-ai-toolkit vX.Y.Z ... -->
    workspace_version=$(sed -n 's/.*vnext-ai-toolkit v\([0-9][0-9.]*\).*/\1/p' CLAUDE.md | head -1)
fi
workspace_runtime=$(scrape runtimeVersion vnext.config.json)

# newest of two versions per sort -V (empty when equal)
newer() { [ "$1" = "$2" ] && return; printf '%s\n%s\n' "$1" "$2" | sort -V 2>/dev/null | tail -1; }

msg=""
if [ -z "$workspace_version" ]; then
    msg="[vnext-ai-toolkit] This vNext workspace has no toolkit version stamp. Its CLAUDE.md/AGENTS.md/.claude/references files may be outdated (installed plugin: v${plugin_version}). Suggest running /vnext-update once to refresh and stamp them."
elif [ "$workspace_version" != "$plugin_version" ]; then
    if [ "$(newer "$workspace_version" "$plugin_version")" = "$plugin_version" ]; then
        msg="[vnext-ai-toolkit] Workspace toolkit files are from v${workspace_version} but the installed plugin is v${plugin_version}. Suggest the user run /vnext-update to refresh CLAUDE.md, AGENTS.md and .claude/references."
    else
        msg="[vnext-ai-toolkit] Workspace toolkit stamp (v${workspace_version}) is NEWER than the installed plugin (v${plugin_version}). The plugin may be outdated: suggest claude plugin marketplace update burgan-tech."
    fi
fi

if [ -n "$known_runtime" ] && [ -n "$workspace_runtime" ] && [ "$known_runtime" != "$workspace_runtime" ]; then
    if [ "$(newer "$workspace_runtime" "$known_runtime")" = "$known_runtime" ]; then
        rmsg="[vnext-ai-toolkit] Workspace targets runtime v${workspace_runtime}; the toolkit's knowledge describes v${known_runtime}. Features whose since-version is above v${workspace_runtime} in .claude/references/runtime-feature-matrix.md are NOT available in this workspace - check before suggesting them. To bump runtimeVersion/schemaVersion run /vnext-init (Step 2)."
    else
        rmsg="[vnext-ai-toolkit] Workspace targets runtime v${workspace_runtime} but the toolkit's knowledge only covers v${known_runtime}. Treat guidance about newer runtime behaviour as unverified; suggest claude plugin marketplace update burgan-tech."
    fi
    msg="${msg:+$msg }$rmsg"
fi

[ -n "$msg" ] || exit 0
# Messages contain no quotes/backslashes/newlines, so no JSON escaping is needed.
printf '{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"%s"}}\n' "$msg"
exit 0
