#!/bin/sh
# vnext-ai-toolkit SessionStart hook.
# Warns (via additionalContext) when the workspace's toolkit-owned files were generated by an
# older plugin version than the one currently installed. Never blocks: always exits 0.
# No jq dependency — plain grep/sed JSON scraping is enough for the two flat fields we read.

# Not a vNext workspace → silent no-op (this hook fires in every project; plugins are global).
[ -f "vnext.config.json" ] || exit 0

plugin_manifest="${CLAUDE_PLUGIN_ROOT}/.claude-plugin/plugin.json"
[ -f "$plugin_manifest" ] || exit 0

# "version": "X.Y.Z"
plugin_version=$(sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$plugin_manifest" | head -1)
[ -n "$plugin_version" ] || exit 0

workspace_version=""
if [ -f ".claude/vnext-toolkit.json" ]; then
    workspace_version=$(sed -n 's/.*"toolkitVersion"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' ".claude/vnext-toolkit.json" | head -1)
fi
if [ -z "$workspace_version" ] && [ -f "CLAUDE.md" ]; then
    # <!-- vnext-ai-toolkit vX.Y.Z ... -->
    workspace_version=$(sed -n 's/.*vnext-ai-toolkit v\([0-9][0-9.]*\).*/\1/p' CLAUDE.md | head -1)
fi

emit() {
    # JSON-escape is unnecessary: messages below contain no quotes/backslashes/newlines.
    printf '{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"%s"}}\n' "$1"
}

if [ -z "$workspace_version" ]; then
    emit "[vnext-ai-toolkit] This vNext workspace has no toolkit version stamp. Its CLAUDE.md/AGENTS.md/.claude/references files may be outdated (installed plugin: v${plugin_version}). Suggest running /vnext-update once to refresh and stamp them."
    exit 0
fi

if [ "$workspace_version" = "$plugin_version" ]; then
    exit 0
fi

# Different versions. sort -V tells us which side is newer (fallback: plain inequality warning).
newest=$(printf '%s\n%s\n' "$workspace_version" "$plugin_version" | sort -V 2>/dev/null | tail -1)
if [ "$newest" = "$plugin_version" ]; then
    emit "[vnext-ai-toolkit] Workspace toolkit files are from v${workspace_version} but the installed plugin is v${plugin_version}. Suggest the user run /vnext-update to refresh CLAUDE.md, AGENTS.md and .claude/references."
else
    emit "[vnext-ai-toolkit] Workspace toolkit stamp (v${workspace_version}) is NEWER than the installed plugin (v${plugin_version}). The plugin may be outdated: suggest claude plugin marketplace update burgan-tech."
fi

exit 0
