#!/bin/sh
# Regenerates references/runtime-feature-matrix.md from the @burgan-tech/vnext-meta JSON bundle
# and stamps the known runtime/schema versions into .claude-plugin/plugin.json (vnext.known*).
#
# Usage:
#   scripts/sync-vnext-meta.sh [--from <vnext-meta dir>]   (default: ../vnext/vnext-meta)
#   scripts/sync-vnext-meta.sh --npm [<version>]           (npm pack @burgan-tech/vnext-meta into a temp dir)
#   scripts/sync-vnext-meta.sh --check                      (exit 1 if the matrix would change; for CI)
#
# Needs: node >= 18. No jq. Idempotent: running twice produces no diff.
set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
src="$here/../vnext/vnext-meta"
mode=write
while [ $# -gt 0 ]; do
  case "$1" in
    --from) src="$2"; shift 2 ;;
    --npm)
      ver=""; if [ $# -gt 1 ] && [ "${2#-}" = "$2" ]; then ver="$2"; shift; fi
      tmp=$(mktemp -d)
      ( cd "$tmp" && npm pack "@burgan-tech/vnext-meta${ver:+@$ver}" >/dev/null && tar xzf ./*.tgz )
      src="$tmp/package"; shift ;;
    --check) mode=check; shift ;;
    -h|--help) sed -n '2,10p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

[ -f "$src/features.json" ] || { echo "vnext-meta not found at $src (use --from or --npm)" >&2; exit 1; }

out="$here/references/runtime-feature-matrix.md"
tmpout=$(mktemp)
META_DIR="$src" OUT="$tmpout" PLUGIN_JSON="$here/.claude-plugin/plugin.json" MODE="$mode" node - <<'NODE'
const fs = require('fs'), path = require('path');
const dir = process.env.META_DIR;
const load = f => JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8'));
const pkg = load('package.json'), features = load('features.json'), manifest = load('version-manifest.json');
const deprecations = load('deprecations.json').items, migrations = load('migrations.json').items;
const knownIssues = load('known-issues.json').items, security = load('security-policy.json');
const perf = load('performance-profiles.json').profiles, registry = load('component-registry.json');

const runtime = features.runtimeVersion;
const schema = (manifest.versions[runtime] || {}).schemaVersion || '';
const semver = (a, b) => { const x = a.split('.').map(Number), y = b.split('.').map(Number);
  for (let i = 0; i < 3; i++) if ((x[i]||0) !== (y[i]||0)) return (x[i]||0) - (y[i]||0); return 0; };
const esc = s => String(s == null ? '' : s).replace(/\|/g, '\\|').replace(/\r?\n/g, ' ').trim();
const first = s => { const m = String(s || '').match(/^(.*?[.!?])(\s|$)/); return esc(m ? m[1] : s); };
const code = s => s ? '`' + esc(s) + '`' : '';
const list = a => Array.isArray(a) ? a.map(code).join(', ') : code(a);

const L = [];
L.push(`<!-- GENERATED by scripts/sync-vnext-meta.sh from @burgan-tech/vnext-meta ${pkg.version} — runtime ${runtime}, schema ${schema}. Do not edit by hand; re-run the script. -->`);
L.push(`# vNext runtime feature matrix`);
L.push('');
L.push(`Snapshot of the machine-readable runtime metadata (\`@burgan-tech/vnext-meta\` **${pkg.version}**). Known runtime version: **${runtime}**, matching schema version: **${schema}**.`);
L.push('');
L.push('How to read it: a workspace whose `vnext.config.json` `runtimeVersion` is **older** than a row\'s `since` does not have that feature. Anything the toolkit references (skills, references) that is newer than the workspace runtime must be treated as unavailable there. The hand-written references under `references/concepts/` explain *how* to use each feature; this file only answers *since when* and *is it still there*.');
L.push('');

// Versions
const versions = Object.keys(manifest.versions).sort(semver).reverse();
L.push('## Runtime → schema versions (latest 15)');
L.push('');
L.push('| Runtime | Schema | Released | Release notes |');
L.push('|---|---|---|---|');
for (const v of versions.slice(0, 15)) { const e = manifest.versions[v];
  L.push(`| ${v} | ${esc(e.schemaVersion)} | ${esc(e.releasedAt)} | ${e.releaseNotes ? esc(e.releaseNotes) : ''} |`); }
L.push('');

// Task types from schemaPath "task.type=N" and registry
L.push('## Task types mentioned in metadata');
L.push('');
L.push('Full catalog with routing and config: `references/concepts/task-types.md`. This table only lists types that vnext-meta itself references.');
L.push('');
L.push('| Type | Feature / registry entry | Since | Status |');
L.push('|---|---|---|---|');
const taskRows = [];
for (const [id, f] of Object.entries(features.engine)) {
  const sp = Array.isArray(f.schemaPath) ? f.schemaPath.join(' ') : String(f.schemaPath || '');
  const m = sp.match(/task\.type\s*=\s*(\d+)/i) || String(f.description||'').match(/TaskType\s*=\s*(\d+)/);
  if (m) taskRows.push([Number(m[1]), id, f.since, f.status]);
}
for (const t of registry.tasks || []) taskRows.push([t.key === 'fanout' ? 21 : '?', `registry:${t.key}`, t.since, t.stable ? 'stable' : 'experimental']);
taskRows.sort((a, b) => (a[0] === '?' ? 99 : a[0]) - (b[0] === '?' ? 99 : b[0]));
for (const r of taskRows) L.push(`| ${r[0]} | ${code(r[1])} | ${esc(r[2])} | ${esc(r[3])} |`);
L.push('');

// Features
L.push('## Engine features');
L.push('');
L.push('| Feature id | Since | Status | Schema path | Summary | API endpoints |');
L.push('|---|---|---|---|---|---|');
const feats = Object.entries(features.engine).sort((a, b) => semver(b[1].since || '0.0.0', a[1].since || '0.0.0') || a[0].localeCompare(b[0]));
for (const [id, f] of feats) L.push(`| ${code(id)} | ${esc(f.since)} | ${esc(f.status)} | ${list(f.schemaPath)} | ${first(f.description)} | ${list(f.apiEndpoints)} |`);
L.push('');

// Deprecations
L.push('## Deprecations');
L.push('');
L.push('| Id | Component | Path | Deprecated since | Removed at | Replacement | Severity |');
L.push('|---|---|---|---|---|---|---|');
for (const d of [...deprecations].sort((a, b) => semver(b.deprecatedSince || '0.0.0', a.deprecatedSince || '0.0.0')))
  L.push(`| ${code(d.id)} | ${esc(d.component)} | ${code(d.path)} | ${esc(d.deprecatedSince)} | ${esc(d.removedAt) || '—'} | ${esc(d.replacement) || '—'} | ${esc(d.severity)} |`);
L.push('');

// Migrations
L.push('## Migrations (behaviour changes to re-check when bumping runtimeVersion)');
L.push('');
L.push('| Id | Since | Severity | Component | Title | Action |');
L.push('|---|---|---|---|---|---|');
for (const m of [...migrations].sort((a, b) => semver(b.since || '0.0.0', a.since || '0.0.0')))
  L.push(`| ${code(m.id)} | ${esc(m.since)} | ${esc(m.severity)} | ${esc(m.component)} | ${esc(m.title)} | ${first(m.action)} |`);
L.push('');

// Known issues (open)
L.push('## Known issues');
L.push('');
L.push('| Id | Affected | Fixed in | Severity | Component | Title | Workaround |');
L.push('|---|---|---|---|---|---|---|');
for (const k of knownIssues) L.push(`| ${code(k.id)} | ${esc(k.affectedVersions)} | ${esc(k.fixedIn) || 'open'} | ${esc(k.severity)} | ${esc(k.component)} | ${esc(k.title)} | ${first(k.workaround)} |`);
L.push('');

// Security policies
L.push('## Security policies');
L.push('');
L.push('| Id | Scope | Enforced since | Error code | HTTP | Description |');
L.push('|---|---|---|---|---|---|');
for (const p of security.policies || []) L.push(`| ${code(p.id)} | ${esc(p.scope)} | ${esc(p.enforcedSince)} | ${code(p.errorCode)} | ${esc(p.httpStatus)} | ${first(p.description)} |`);
L.push('');

// Performance profiles
L.push('## Performance profiles (documented limits / defaults)');
L.push('');
L.push('| Id | Since | Scope | Configuration (default) | Description |');
L.push('|---|---|---|---|---|');
for (const p of perf || []) {
  const cfg = Object.entries(p.configuration || {}).map(([k, v]) => `\`${k}\`=${esc(JSON.stringify(v.default))}`).join(', ');
  L.push(`| ${code(p.id)} | ${esc(p.since)} | ${esc(p.scope)} | ${cfg} | ${first(p.description)} |`);
}
L.push('');
L.push('## Sources');
L.push('');
L.push(`- \`@burgan-tech/vnext-meta\` ${pkg.version} (repo dir \`vnext/vnext-meta\`): features.json, version-manifest.json, deprecations.json, migrations.json, known-issues.json, security-policy.json, performance-profiles.json, component-registry.json`);
L.push('- Regenerate: `scripts/sync-vnext-meta.sh --from ../vnext/vnext-meta` (or `--npm`).');
L.push('');
fs.writeFileSync(process.env.OUT, L.join('\n'));

// plugin.json stamps (string replace to keep formatting stable)
if (process.env.MODE === 'write') {
  const pj = process.env.PLUGIN_JSON; let txt = fs.readFileSync(pj, 'utf8');
  const stamps = { knownRuntimeVersion: runtime, knownSchemaVersion: schema, metaPackageVersion: pkg.version };
  for (const [k, v] of Object.entries(stamps)) {
    const re = new RegExp(`("${k}"\\s*:\\s*")[^"]*(")`);
    if (re.test(txt)) txt = txt.replace(re, `$1${v}$2`);
    else txt = txt.replace(/("vnext"\s*:\s*\{)/, `$1\n    "${k}": "${v}",`);
  }
  fs.writeFileSync(pj, txt);
}
console.log(`vnext-meta ${pkg.version}: runtime ${runtime}, schema ${schema}`);
NODE

if [ "$mode" = check ]; then
  if cmp -s "$tmpout" "$out"; then echo "runtime-feature-matrix.md is up to date"; rm -f "$tmpout"; exit 0; fi
  echo "runtime-feature-matrix.md is stale — run scripts/sync-vnext-meta.sh" >&2; diff "$out" "$tmpout" | head -20 >&2; rm -f "$tmpout"; exit 1
fi
mv "$tmpout" "$out"
echo "wrote $out"
